apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
  namespace: test
spec:
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: docker.io/burakovali/go-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2000
